In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


## Load Dataset

In [9]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [5]:
print(type(iris_dataset))

<class 'sklearn.utils._bunch.Bunch'>


## Information about dataset

In [14]:
print(f'Keys:\n{iris_dataset.keys()}')

Keys:
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [17]:
print(f'Feature Names:\n',iris_dataset['feature_names'])

Feature Names:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
print('First Five rows:\n',iris_dataset['data'][:5])

First Five rows:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [21]:
print('Shape:\n',iris_dataset['data'].shape)

Shape:
 (150, 4)


## Information about target

In [31]:
print('Target:\n',iris_dataset['target'])

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [29]:
print('Type of Target:\n',type(iris_dataset['target']))

Type of Target:
 <class 'numpy.ndarray'>


In [33]:
print('Target Values:\n',iris_dataset['target_names'])

Target Values:
 ['setosa' 'versicolor' 'virginica']


In [30]:
print('Shape oftarget values:\n',iris_dataset['target'].shape)

Shape oftarget values:
 (150,)


## Describe Dataset

In [34]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

## Simple Model Training KNN

In [35]:
X = iris_dataset['data']
y = iris_dataset['target']

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
kNN = KNeighborsClassifier()

### Training

In [40]:
kNN.fit(X, y)

KNeighborsClassifier()

### Testing

In [43]:
import numpy as np
test = np.array([[3, 4.5, 1, 0.5]])
print(test.shape)

(1, 4)


In [44]:
prediction = kNN.predict(test)

In [45]:
print('Prediction:\n',prediction)

Prediction:
 [0]


In [46]:
print('Predicted Flower is:\n',iris_dataset['target_names'][prediction])

Predicted Flower is:
 ['setosa']
